services:
  mysql:
    image: mysql:8.4.2
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mycoda
      MYSQL_ROOT_PASSWORD: [[ MySQL Password ]]
    restart: unless-stopped

  mycoda:
    image: macodaclub/mycoda:[[ Image Version ]]
    command: -sslPort=443 -sslKeyStore=/backend/keystore.jks
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - [[ SSL Certificate JKS File Path ]]:/backend/keystore.jks
      - /var/log/server-logs:/backend/logs
    environment:
      SSL_KEY_ALIAS: [[ SSL Certificate JKS Alias ]]
      SSL_KEYSTORE_PASSWORD: [[ SSL Certificate JKS Password ]]
      SSL_PRIVATE_KEY_PASSWORD: [[ SSL Certificate PK Password ]]
      GITHUB_OAUTH: [[ GitHub OAuth Token ]]
      HOST_NAME: [[ Domain Name ]]
      MYCODA_ONTOLOGY_URL: https://raw.githubusercontent.com/macodaclub/MyCODA/refs/heads/main/ontologies/MaCODA.owl
      MYCODA_ONTOLOGY_IRI_PREFIX: https://mycoda.ddns.net/ontologies/MYCODA
      CURATOR_PASSWORD: [[ Curator Password ]]
      LOGS_FOLDER_PATH: /backend/logs
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: [[ MySQL Password ]]
      MYSQL_DATABASE: mycoda
    restart: unless-stopped

volumes:
  mysql-data:
  logs:
