services:
  mysql:
    image: mysql:8.4.2
    ports:
      - "8082:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mycoda
      MYSQL_ROOT_PASSWORD: password

  mycoda:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./backend/.github:/backend/.github
#      - logs:/backend/logs
    environment:
#      LOGS_FOLDER_PATH: XXXXXX
      MYCODA_ONTOLOGY_IRI_PREFIX: https://mycoda.ddns.net/ontologies/MYCODA
      MYCODA_ONTOLOGY_URL: https://raw.githubusercontent.com/macodaclub/MyCODA/refs/heads/main/ontologies/MaCODA.owl
      GITHUB_REPO_URL: https://github.com/macodaclub/MyCODA
      CURATOR_PASSWORD: password
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mycoda
      GITHUB_PROPERTY_FILE_PATH: /backend/.github

volumes:
  mysql-data:
#  logs:
