ktor:
  application:
    modules:
      - "io.github.macodaclub.ApplicationKt.module"
  development: "$DEVELOPMENT:false"
  deployment:
    port: "$PORT:80"
  frontendPort: "$FRONTEND_PORT:null"
  hostName: "$HOST_NAME:null"
  security:
    ssl:
      keyAlias: "$SSL_KEY_ALIAS:null"
      keyStorePassword: "$SSL_KEYSTORE_PASSWORD:null"
      privateKeyPassword: "$SSL_PRIVATE_KEY_PASSWORD:null"