name: Reload ontology

on:
  push:
    branches:
      - main
    paths:
      - "ontologies/MaCODA.owl"

jobs:
  reload:
    runs-on: self-hosted

    steps:
    - name: Debug secret length
      env:
        RELOAD_SECRET: ${{ secrets.RELOAD_ONTOLOGY_SECRET }}
      run: |
        echo "Secret length: ${#RELOAD_SECRET}"